# push 동작을 할떄 동작하도록
on: push
name: make Debug apk
jobs:
#  tag:
#    name: Tag
#    runs-on: ubuntu-latest
#    steps:
#      - name: Get current date
#        id: date
#        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
#
#      - name: Commit tagger
#        uses: tvdias/github-tagger@v0.0.2
#        with:
#          repo-token: ${{ secrets.TOKEN_GITHUB }}
#          tag: ${{ steps.date.outputs.date }}

  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # 자바 버전 설정
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v1
        with:
          #          flutter-version: '2.8.0'
          channel: 'stable'

      # google-json test
      - name: Make google-services.json
        run: echo '${{ secrets.GOOGLE_SERVICES }}' > android/app/google-services.json

      - run: flutter pub get
      - run: flutter test

      # apk 작성
      - name: build apk
        run: flutter build apk --debug

      - name: upload apk
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*.apk"
          token: ${{ secrets.TOKEN_GITHUB }}

#      - name: upload artifacts
#        uses: actions/upload-artifact@master
#        with:
#          name: apk-debug
#          path: build/app/outputs/apk/debug/app-debug.apk


      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.2
        with:
          appId: ${{ secrets.FIREBASE_APP_ID_ANDROID }}
          token: ${{ secrets.FIREBASE_TOKEN}}
          groups: testers
          file: build/app/outputs/apk/debug/app-debug.apk